package com.grab.tools.analyzer.mapper


import com.grab.tools.analyzer.model.ClassFileInfo
import com.grab.tools.parser.AarFileInfo
import com.grab.tools.parser.ApkFileInfo
import com.grab.tools.parser.JarFileInfo
import javax.inject.Inject

private const val AUTO_GENERATION_LAMBDA = "-\$\$Lambda\$"

internal class ClassesComponentMapper @Inject constructor() : ComponentMapper {
    override fun analyze(
        apks: Set<ApkFileInfo>,
        aars: Set<AarFileInfo>,
        jars: Set<JarFileInfo>
    ): ComponentMapperResult {
        val apkClasses = apks.flatMap { apk -> apk.dexes }.flatMap { dex -> dex.classes }
        val libClassMap = mutableMapOf<ClassFileInfo, String>().apply {
            aars.forEach { aar ->
                aar.jars.forEach { jar ->
                    jar.classes.forEach { clazz ->
                        put(clazz, aar.path)
                    }
                }
            }
            jars.forEach { jar ->
                jar.classes.forEach { clazz ->
                    put(clazz, jar.path)
                }
            }
        }
        val noOwnerClasses = mutableSetOf<ClassFileInfo>()
        val contributors = mutableMapOf<String, MutableSet<ClassFileInfo>>().apply {
            apkClasses.forEach { clazz ->
                val libName = libClassMap[clazz]?: libClassMap[clazz.tryOriginalClass()]
                if (libName != null) {
                    putIfAbsent(libName, mutableSetOf())
                    get(libName)?.add(clazz)
                } else {
                    noOwnerClasses.add(clazz)
                }
            }
        }
        return ComponentMapperResult(
            contributors = contributors,
            noOwnerData = noOwnerClasses
        )
    }

    private fun ClassFileInfo.tryOriginalClass(): ClassFileInfo {
        /**
         * Auto generated lambda. Possible it's generated by R8
         * Ex: androidx.core.widget.-$$Lambda$ContentLoadingProgressBar$aW9csiS0dCdsR2nrqov9CuXAmGo
         */
        if (name.contains(AUTO_GENERATION_LAMBDA)) {
            var newName = name.replace(AUTO_GENERATION_LAMBDA, "")
            if(newName.lastIndexOf("$") > 0)
                newName = newName.removeRange(newName.lastIndexOf("$"), newName.length)
            return copy(name = newName)
        }
        return this
    }
}