default:
  image: gitlab.myteksi.net:4567/mobile/pax-android/basic-docker:1.0.1

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish

build:
  stage: build
  script: ./gradlew gradle-plugin:assemble --rerun-tasks
  tags:
    - xlarge
  artifacts:
    paths:
      - gradle-plugin/build/libs/*.jar
      - clt/build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  tags:
    - xlarge
  script:
    - cd ./sample
    - ./gradlew app:appSizeAnalysisGpsRelease --stacktrace -Dorg.gradle.debug=false --no-daemon --info

publish_artifact:
  stage: publish
  rules:
    - if: $RELEASE == "publish"
  tags:
    - xlarge
  script:
    - ./gradlew artifactoryPublish