buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.24.20"
    }
}

subprojects {
    group = 'com.grab'
    version = System.getenv("CI")?.toBoolean() ? "SNAPSHOT-01" : "SNAPSHOT"
}


