apkDirectoryPath: "/apk5191"
libraryDirectoryPath: "/gradle-cache-5191/caches/modules-2"
projectDirectoryPath: "/pax-android"
outputFilePath: "/output.xls"
mappingFilePath: "/apk5191/mapping.txt"
featureMappingFilePath: "/pax-android/module-owner.yml"
deviceName: "oppo"
projectName: "pax-android"
extraTag: "10000"