plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.grab.android.sample'
    compileSdk 34

    defaultConfig {
        applicationId "com.grab.android.sample"
        archivesBaseName = "sample-bundle-file"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "0.0.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
    }

    signingConfigs {
        release {
            // You need to specify these in your local.properties file or
            // as environment variables
            storeFile file("$rootProject.projectDir/buildsystem/sample-release.keystore")
            storePassword '12345678'
            keyAlias 'key0'
            keyPassword '12345678'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }


    flavorDimensions += "version"
    productFlavors {
        // flavor for production
        pro {
            dimension = "version"
            applicationIdSuffix = ".pro"
            versionNameSuffix = "-pro"
        }
        // flavor for early access
        gea {
            dimension "service"
            applicationIdSuffix = ".gea"
            versionNameSuffix = "-gea"
        }
    }
}


dependencies {
    implementation project(":android-module-level1")
    implementation project(":kotlin-module")
    implementation libs.androidx.appcompat
    implementation libs.androidx.navigation.ktx
    implementation libs.androidx.navigation.fragment.ktx
    testImplementation libs.junit
}

apply plugin: "com.grab.app-sizer"

appSizeAnalysis {
    enabled = true
    projectInput {
        apk {
            bundleToolFile = file("${rootProject.rootDir}/binary/bundletool-all-1.15.4.jar")
            deviceSpecs = [
                    file("${rootProject.rootDir}/app-size-config/device-1.json"),
                    file("${rootProject.rootDir}/app-size-config/device-2.json")
            ]
        }
        variantFilter { variant ->
            variant.setIgnore(variant.flavors.contains("gea"))
        }
        enableMatchDebugVariant = true
        largeFileThreshold = 10
        teamMappingFile = file("${rootProject.rootDir}/module-owner.yml")
    }
    metrics {
        /** Enable this block if you have an InfluxDb locally **/
        /**
        influxDB {
            dbName = "sizer"
            reportTableName = "app_size"
            url = "http://localhost:8086"
            username = "root"
            password = "root"
            retentionPolicy {
                name = "app_sizer"
                duration = "360d"
                shardDuration = "0m"
                replicationFactor = 2
                setAsDefault = true
            }
        }**/
        customAttributes.putAll(
                ["pipeline_id": "1001"]
        )
    }
}