plugins {
    id 'java-gradle-plugin'
    id "org.gradle.kotlin.kotlin-dsl" version "2.3.3"
}


repositories {
    google()
    mavenCentral()
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
    maven {
        setUrl("https://artifacts.gitlab.myteksi.net/artifactory/mobile--android")
        credentials {
            username = "svc.eng.gfinmobile"
            password = "cmVmdGtuOjAxOjE3NDU2NTU0MTE6aUpQVjFseTRLd1RDNTU4TnZMYjZCQzJaVGFY"
        }
    }
}

dependencies {
    implementation libs.kotlin.gradle.plugin
    implementation libs.mobile.publish
}

gradlePlugin {
    plugins {
        sizerKotlinBuildPlugin {
            id = 'com.grab.sizer.build'
            implementationClass = 'com.grab.sizer.buildplugins.AppSizerConfigPlugin'
        }
    }
}