plugins {
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.kapt"
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation project(":report-writer")
    implementation project(":agent-report")
    implementation libs.dexlib2
    implementation libs.clikt
    implementation libs.bundletool
    implementation libs.apkanalyzer
    implementation libs.common
    implementation libs.jackson.module.kotlin
    implementation libs.jackson.dataformat.yaml
    implementation libs.kxml2
    implementation libs.guava
    implementation libs.poi.ooxml
    implementation libs.jxls.jexcel
    implementation libs.google.dagger
    kapt libs.dagger.compiler
    implementation libs.gson
    testImplementation libs.kotlin.test
}