[versions]
gradle-plugin-publish = "2.1.1"
android-gradle-plugin = "9.0.1"
kotlin = "2.3.21"
dagger = "2.60.1"
dexlib2 = "2.5.2"
clikt = "4.4.0"
bundletool = "1.18.1"
apkanalyzer = "32.0.1"
common = "32.0.1"
jackson = "2.15.0"
guava = "33.2.1-jre"
gson = "2.10.1"
influxdbClient = "2.24"
shadow-jar = "9.0.2"
nexus = "2.0.0"
dokka = "2.1.0"

# Tests
junit = "4.13.2"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle-plugin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
google-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
org-smali-dexlib2 = { module = "org.smali:dexlib2", version.ref = "dexlib2" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
android-tools-bundletool = { module = "com.android.tools.build:bundletool", version.ref = "bundletool" }
android-tools-apkanalyzer = { module = "com.android.tools.apkparser:apkanalyzer", version.ref = "apkanalyzer" }
android-tools-common = { module = "com.android.tools:common", version.ref = "common" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
org-influxdb-client = { module = "org.influxdb:influxdb-java", version.ref = "influxdbClient" }
nexus-gradle-publish-plugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus" }

# Tests
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "shadow-jar" }
dokka-gradle-plugin = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }

