plugins {
    id "com.grab.sizer.build"
}

dependencies {
    implementation libs.influxdbClient
    implementation libs.dexlib2
    implementation libs.clikt
    implementation libs.bundletool
    implementation libs.apkanalyzer
    implementation libs.common
    implementation libs.jackson.module.kotlin
    implementation libs.jackson.dataformat.yaml
    implementation libs.kxml2
    implementation libs.guava
    implementation libs.poi.ooxml
    implementation libs.google.dagger
    implementation libs.gson

    kapt libs.dagger.compiler

    testImplementation libs.kotlin.test
}

ext.artifactId = "app-sizer"