plugins {
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.kapt"
    id "com.grab.sizer.kotlin.buildplugin"
}

dependencies {
    implementation project(":agent-report")
    implementation('org.apache.poi:poi-ooxml:5.2.2')
    implementation('org.jxls:jxls-jexcel:1.0.9')
    implementation libs.influxdbClient

    implementation libs.dexlib2
    implementation libs.clikt
    implementation libs.bundletool
    implementation libs.apkanalyzer
    implementation libs.common
    implementation libs.jackson.module.kotlin
    implementation libs.jackson.dataformat.yaml
    implementation libs.kxml2
    implementation libs.guava
    implementation libs.poi.ooxml
    implementation libs.jxls.jexcel
    implementation libs.google.dagger
    implementation libs.gson

    kapt libs.dagger.compiler

    testImplementation libs.kotlin.test
}


group = 'com.grab'
version = "SNAPSHOT"
def libArtifactId = 'app-sizer'

apply from: '../publish.gradle'
configureArtifact(group, version, libArtifactId)

repositories {
    mavenCentral()
}
