{
 "title": "App Download Size Breakdown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_version",
    "label": "App Version",
    "query": "select DISTINCT(\"app_version\") from (select * from \"app_size\") "
   },
   {
    "name": "reference_device",
    "label": "Reference Device",
    "query": "select DISTINCT(\"device_name\") from (select * from \"app_size\") "
   },
   {
    "name": "tf_name",
    "label": "Team name",
    "query": "select DISTINCT(\"owner\") from (select * from \"app_size\") where \"owner\" != 'NA'"
   }
  ]
 },
 "panels": [
  {
   "title": "App Download Size Trending",
   "type": "timeseries",
   "description": "This graph illustrates the trend of app download sizes, grouped by their respective app versions. You have the option to apply a filter based on the Reference Device.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Hover value",
     "query": "SELECT \"size\" FROM \"app_size\" WHERE (\"type\" = 'apk_basic' and \"contributor\"= 'apk' and \"device_name\" =~ /^$reference_device$/ ) AND $timeFilter "
    },
    {
     "alias": "App Download Size for $tag_app_version",
     "query": "SELECT \"size\" FROM \"app_size\" WHERE (\"type\" = 'apk_basic' and \"contributor\"= 'apk' and \"device_name\" =~ /^$reference_device$/ ) AND $timeFilter GROUP BY \"app_version\""
    }
   ]
  },
  {
   "title": "App Download Size Breakdown by Components",
   "type": "piechart",
   "description": "A graph representation of the breakdown of the App Download Size by individual components. You have the option to filter by App Version, Reference Device",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_contributor",
     "query": "SELECT last(\"size\") FROM \"app_size\" WHERE (\"type\" = 'apk' AND \"app_version\" =~ /^$app_version$/ AND \"device_name\" =~ /^$reference_device$/ AND \"contributor\" != 'apk' AND $timeFilter )  GROUP BY \"contributor\""
    }
   ]
  },
  {
   "title": "App Download Size Breakdown by Teams",
   "type": "piechart",
   "description": "A roster of teams, each accompanied by the corresponding size of their contribution to the total app download size. \nYou could filter by the App Version and the Reference Device",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_owner",
     "query": "SELECT last(\"size\")\nFROM \"app_size\"\nWHERE (\n  \"type\" = 'team'\n  AND \"contributor\" = 'total'\n  AND \"app_version\"  =~ /^$app_version$/\n  AND \"device_name\"  =~ /^$reference_device$/\n  AND $timeFilter\n)\nGROUP BY \"owner\""
    }
   ]
  },
  {
   "title": "App Download Size Breakdown by Libraries",
   "type": "piechart",
   "description": "A compilation of libraries, each denoted with the size it contributes to the overall App Download Size. You have the option to filter by App Version and Reference Device.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_contributor",
     "query": "SELECT last(\"size\") FROM \"app_size\" WHERE (\"type\" = 'library' AND \"app_version\" =~ /^$app_version$/ AND \"device_name\" =~ /^$reference_device$/ AND $timeFilter )  GROUP BY \"contributor\"\n"
    }
   ]
  },
  {
   "title": "Team Breakdown (Select the team name to see the detail)",
   "type": "piechart",
   "description": "A list of module names/libraries associated with the selected 'Team Name' filter, accompanied by a graph illustrating the contribution of each module to the app download size.\nYou have the option to filter by App Version, Reference Device, and Team Name",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_contributor",
     "query": "SELECT last(\"size\") FROM \"app_size\"\nWHERE (\"type\" = 'module'\n       AND \"app_version\" =~ /^$app_version$/\n       AND \"device_name\" =~ /^$reference_device$/\n       AND \"owner\"       =~ /^$tf_name$/)\nGROUP BY \"contributor\""
    },
    {
     "alias": "$tag_contributor",
     "query": "SELECT last(\"size\") FROM \"app_size\"\nWHERE (\"type\" = 'library'\n       AND \"app_version\" =~ /^$app_version$/\n       AND \"device_name\" =~ /^$reference_device$/\n       AND \"owner\"       =~ /^$tf_name$/)\nGROUP BY \"contributor\""
    }
   ]
  },
  {
   "title": "Team Breakdown by main Components (Select the team name to see the detail)",
   "type": "piechart",
   "description": "A graph representation of the breakdown of the Team Download Size by individual components. You have the option to filter by App Version, Reference Device, and Team name",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_contributor",
     "query": "SELECT last(\"size\")\nFROM \"app_size\"\nWHERE (\n  \"type\"        = 'team'\n  AND \"contributor\" != 'total'\n  AND \"app_version\" =~ /^$app_version$/\n  AND \"owner\" =~ /^$tf_name$/\n  AND \"device_name\" =~ /^$reference_device$/\n  AND $timeFilter\n)\nGROUP BY \"contributor\""
    }
   ]
  },
  {
   "title": "Large Files",
   "type": "table",
   "description": "A list of files exceeding the size threshold as set in the app-sizer configuration. You can apply filters based on App Version and Reference Device.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT last(\"size\") as Size , \"contributor\" as \"File Name\",  \"owner\" as Owner FROM \"app_size\" WHERE (\"type\" = 'large_file' AND \"app_version\" =~ /^$app_version$/ AND \"device_name\" =~ /^$reference_device$/ AND $timeFilter )  group by \"contributor\"\n"
    }
   ]
  }
 ]
}