// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.grab:sizer-analysis:SNAPSHOT"
    }
}

plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.20' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.8.20' apply false
}

apply plugin: "com.grab.sizer-analysis"

appSizeAnalysis {
    apk {
        bundleToolPath = new File(project.rootDir, '/binary/bundletool-all-1.15.4.jar').toString()
        bundleFilePath = "${project.rootDir}/app/build/outputs/bundle/gpsRelease/app-gps-release.aab"
    }

    metrics {
        influxDbPublisher {
            dbName = "sizer"
            url = "http://10.197.86.135:8086"
            username = "talaiot"
            password = "UrMpvi3uC6Wc1owj"
        }
        local {
            outputDirectory = new File(project.buildDir, "sizer-report")
        }

        customAttributes.putAll(
                ["pipelineId": "100"]
        )
    }
    featureMappingFile = new File(project.rootDir, 'module-owner.yml')
}