package com.grab.sizer.report

import java.io.File
import java.util.*
import javax.inject.Inject

private const val KILO_BYTE = 1024L
private const val MEGA_BYTE = 1024L * 1024L

class MarkdownReportWriter @Inject constructor(
    private val outputDirectory: File
) : ReportWriter {
    override fun write(reportId: String, report: Report) {
        File(File(outputDirectory, report.projectInfo.deviceName), "$reportId-report.md").apply {
            initOutPutFile()
            writeText(
                MarkdownTable(report.createHeader()).apply {
                    report.rows.sortedBy { it.size() }.forEach { row ->
                        addRow(row.toMarkDown())
                    }
                }.generate()
            )
        }
    }

    private fun Row.toMarkDown(): List<String> {
        return fields.map { field ->
            when (field.value) {
                is Long -> (field.value as Long).reportSize()
                else -> field.value.toString()
            }
        }
    }

    private fun Report.createHeader(): List<String> {
        return rows.firstOrNull()?.fields?.map { field ->
            field.name.replaceFirstChar {
                if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
            }
        } ?: emptyList()
    }

    private fun File.initOutPutFile() {
        if (!exists()) {
            if (!parentFile.exists())
                parentFile.mkdirs()
            createNewFile()
        }
    }

    private fun Row.size(): Long = fields.find { it.name == "size" }?.value as Long
}

internal fun Long.reportSize(): String = when {
    this < KILO_BYTE -> "$this bytes"
    this < MEGA_BYTE -> "%.3f KB".format(this.toDouble() / KILO_BYTE)
    else -> "%.3f MB".format(this.toDouble() / MEGA_BYTE)
}

/**
 * A simple class to generate mark-down table
 * It was generated by Chatgpt
 */
class MarkdownTable(private val headers: List<String>) {
    private val rows: MutableList<List<String>> = mutableListOf()

    fun addRow(row: List<String>) {
        require(row.size == headers.size) { "Row has different number of columns compared to headers." }
        rows.add(row)
    }

    fun generate(): String {
        val sb = StringBuilder()
        sb.append("| ")
        headers.forEach { header ->
            sb.append(header)
            sb.append(" | ")
        }
        sb.append("\n| ")
        repeat(headers.size) { sb.append("--- | ") }
        rows.forEach { row ->
            sb.append("\n| ")
            row.forEach { item ->
                sb.append(item)
                sb.append(" | ")
            }
        }
        return sb.toString()
    }
}