plugins {
    id 'java-gradle-plugin'
    id "org.gradle.kotlin.kotlin-dsl" version "2.3.3"
}


repositories {
    google()
    mavenCentral()
    jcenter()
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20")
}

gradlePlugin {
    plugins {
        sizerKotlinBuildPlugin {
            id = 'com.grab.sizer.kotlin.buildplugin'
            implementationClass = 'com.grab.sizer.buildplugins.AppSizerKotlinPlugin'
            displayName = "SizerKotlinBuildPlugin"
        }
    }
}